---
dataset_type: 'image' #Type of data from which to extract scenegraphs from. Options: 'image', 'carla'
location_data:
    #input_path: 'use_case_data/lanechange' #input path to main directory containing driving sequence subdirectories from which to extract scenegraphs
    input_path: ''
    data_save_path: 'use_case_2_sg_extraction_output.pkl' #path to save extracted scenegraph dataset

relation_extraction_settings:
  frames_limit: null #extract scenegraphs for 1 frame every n frames per sequence subdirectory. currently only functional for image based extraction. Options: null(None), Integer n
  ACTOR_NAMES: ["ego_car", 'car','moto','bicycle','ped','lane','light','sign', 'road'] #types of actors that can be found in data sequences. ego_car actor represents the car from whose perspective we are viewing the road. this array's structure is also used for one-hot encoding when creating node embeddings, "ego_car", "lane", "road" are assumed to always be in this list.
  RELATION_NAMES: ['isIn', 'inDFrontOf', 'inSFrontOf', 'atDRearOf', 'atSRearOf', 'toLeftOf', 'toRightOf', 'near_coll', 'super_near' , 'very_near', 'near' ,'visible'] #types of relations to extract
  

   PROXIMITY_THRESHOLDS: [['near_coll',1.5],['super_near',3],['very_near',4],['near',6],['visible',15]] #define proximity relations in the format [relation, distance (ft)] in decreasing order of closeness

  LANE_THRESHOLD: 2 #was 6 feet. if object's center is more than this distance away from ego's center, build left or right lane relation. otherwise build middle lane relation
  DIRECTIONAL_THRESHOLDS: [['isIn',[[0,0]]], ['inDFrontOf',[[45,90],[90,135]]], ['inSFrontOf',[[0,45],[135,180]]], ['atDRearOf',[[225,270],[270,315]]], ['atSRearOf',[[180,225],[315,360]]], ['toLeftOf', [[120, 240]]], ['toRightOf', [[300, 60]]]] #Leftof and Rightof assumed to always be direction relations. additonal directional relations can be specified in the form [[relation], [[1st range of degrees], [2nd range of degrees], ..]]
  RELATION_COLORS: [['isIn','black'],['near_coll','red'], ['super_near','orange'], ['very_near','yellow'], ['near','purple'], ['visible','green'], ['inDFrontOf','violet'], ['inSFrontOf','violet'], ['atDRearOf','turquoise'], ['atSRearOf','turquoise'], ['toLeftOf','blue'], ['toRightOf','blue']] #define relational edge colors for scenegraph visualization purposes in the format [relation, edge_color]
  #proximity_relation_list: [['car','road',30], ['ego_car', 'car',30]] #[[ACTORTYPE1, ACTORTYPE2, max proximity distance before relations are not extracted]]
  proximity_relation_list : [
    ['car', 'road', 20],
    ['ego_car', 'car', 20],
    ['truck', 'road', 20],
    ['ego_car', 'truck', 20]
    ]
  #directional_relation_list: [['car','road',30], ['ego_car', 'car',30]] #[[ACTORTYPE1, ACTORTYPE2, max proximity distance before relations are not extracted]] 
  directional_relation_list : [
    ['car', 'road', 20],
    ['ego_car', 'car', 20],
    ['truck', 'road', 20],
    ['ego_car', 'truck', 20]
    ]
  
  #every type of actor in ACTOR_NAMES can have a list of synonymous names found in the object detection data. for a given ACTOR_NAMES array, all types of objects within the array are treated as objects of type ACTOR.
  MOTO_NAMES: ["moto","Harley-Davidson", "Kawasaki", "Yamaha"]
  BICYCLE_NAMES: ["bicycle","Gazelle", "Diamondback", "Bh"]
  CAR_NAMES: ["car","TRUCK","BUS","Ford", "Bmw", "Toyota", "Nissan", "Mini", "Tesla", "Seat", "Lincoln", "Audi", "Carlamotors", "Citroen", "Mercedes-Benz", "Chevrolet", "Volkswagen", "Jeep", "Nissan", "Dodge", "Mustang"]
  SIGN_NAMES: ["sign"]
  LIGHT_NAMES: ["light"]
  PED_NAMES: []
  ROAD_NAMES: []
  LANE_NAMES: []


image_settings: #path to bev calibration data. only for use with real image scenegraph extraction
    #BEV_PATH: 'use_case_data/bev.json'
    BEV_PATH: 'roadscene2vec/scene_graph/extraction/bev/bev.json'
